CREATE DATABASE GimnasioDB;
GO
USE GimnasioDB;
GO

CREATE TABLE PROFESORES (
    IdProfesor INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Telefono VARCHAR(20),
    Email VARCHAR(100)
);

CREATE TABLE HORARIOS_CLASE (
    IdHorario INT IDENTITY(1,1) PRIMARY KEY,
    DiaSemana VARCHAR(15) NOT NULL,
    HoraInicio TIME NOT NULL,
    CupoMaximo TINYINT NOT NULL,
    IdProfesor INT NOT NULL,
    FOREIGN KEY (IdProfesor) REFERENCES PROFESORES(IdProfesor)
);

CREATE TABLE SOCIOS (
    DNI INT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Telefono VARCHAR(20),
    Email VARCHAR(100),
    FechaNacimiento DATE,
    FechaAlta DATE DEFAULT GETDATE()
);

CREATE TABLE INGRESOS (
    IdIngreso INT IDENTITY(1,1) PRIMARY KEY,
    DNISocio INT NOT NULL,
    FechaHora DATETIME DEFAULT GETDATE(),
    Resultado VARCHAR(20),
    Motivo VARCHAR(255),
    FOREIGN KEY (DNISocio) REFERENCES SOCIOS(DNI)
);

CREATE TABLE PLANES (
    IdPlan INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    DuracionMeses TINYINT NOT NULL,
    Precio DECIMAL(10, 2) NOT NULL
);

CREATE TABLE METODOS_PAGO (
    IdMetodoPago INT IDENTITY(1,1) PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE PAGOS (
    IdPago INT IDENTITY(1,1) PRIMARY KEY,
    DNISocio INT NOT NULL,
    IdPlan INT NOT NULL,
    IdMetodoPago INT NOT NULL,
    FechaPago DATE NOT NULL,
    FechaVencimiento DATE NOT NULL,
    FOREIGN KEY (DNISocio) REFERENCES SOCIOS(DNI),
    FOREIGN KEY (IdPlan) REFERENCES PLANES(IdPlan),
    FOREIGN KEY (IdMetodoPago) REFERENCES METODOS_PAGO(IdMetodoPago)
);

CREATE TABLE INSCRIPCIONES (
    IdInscripcion INT IDENTITY(1,1) PRIMARY KEY,
    DNISocio INT NOT NULL,
    IdHorario INT NOT NULL,
    FechaInscripcion DATE DEFAULT GETDATE(),
    FOREIGN KEY (DNISocio) REFERENCES SOCIOS(DNI),
    FOREIGN KEY (IdHorario) REFERENCES HORARIOS_CLASE(IdHorario)
);